apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-upgrade
		"helm.sh/hook-weight": "5"
		"helm.sh/hook-delete-policy": hook-suceeded # also use 'hook-failed' and 'before-hook-creation'
spec:
	template:
		metadata:
			name: {{ .Release.Name }}-nginx
	spec:
		restartPolicy: never
		containers:
			-	name: pre-upgrade-backup-job
				image: alpine
				command: ["/bin/backup.sh"]